export const SITE_CONFIG = {
  title: 'Hồ Diên Công',
  description: 'I am A Software Engineer. I can build websites, app mobile and API service that best to you',
  images: '/favicon.ico',
  icon: '/favicon.ico',
  keywords: [
    'cong',
    'Hồ Diên Công',
    'Công',
    'ho dien cong',
    'Software Engineer',
    'Công front end',
    'Công full stack',
    'Reactjs',
    'React native',
    'Website',
    'App mobile',
    'API',
    'Backend',
    'Frontend',
  ],
  url: 'https://hdcong.vercel.app/',
}
